# Generated by Django 3.1 on 2020-08-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
        migrations.DeleteModel(
            name='FileTag',
        ),
    ]
