# Generated by Django 3.0.8 on 2020-09-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200827_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.FileField(upload_to=''),
        ),
    ]
